translate portuguese strings:
    old "Self-voicing disabled."
    new "Narração assistiva desabilitada."
    old "Clipboard voicing enabled. "
    new "Narração da área de transferência habilitada. "
    old "Self-voicing enabled. "
    new "Narração assistiva habilitada. "
    old "Font Override"
    new "Substituição de Fonte"
    old "Default"
    new "Padrão"
    old "DejaVu Sans"
    new "DejaVu Sans"
    old "Opendyslexic"
    new "Opendyslexic"
    old "Text Size Scaling"
    new "Escala do Tamanho do Texto"
    old "Reset"
    new "Resetar"
    old "Line Spacing Scaling"
    new "Escala do Espaçamento entre Linhas"
    old "High Contrast Text"
    new "Texto de Alto Contraste"
    old "Enable"
    new "Habilitar"
    old "Disable"
    new "Desabilitar"
    old "Self-Voicing"
    new "Narração Assistiva"
    old "Off"
    new "Desabilitado"
    old "Text-to-speech"
    new "Texto para Fala"
    old "Clipboard"
    new "Área de Transferência"
    old "Debug"
    new "Depurar"
    old "Self-Voicing Volume Drop"
    new "Redução de Volume da Narração Assistiva"
    old "The options on this menu are intended to improve accessibility. They may not work with all games, and some combinations of options may render the game unplayable. This is not an issue with the game or engine. For the best results when changing fonts, try to keep the text size the same as it originally was."
    new "As opções nesse menu visam melhorar a accessibilidade. Elas não vão funcionar com todos os jogos, e algumas combinações de opções podem deixar o game injogável. Isso não é um problema com o jogo ou a engine. Para melhores resultados mudando fontes, tente manter o tamanho do texto igual ao que era originalmente."
    old "{#weekday}Monday"
    new "{#weekday}Segunda"
    old "{#weekday}Tuesday"
    new "{#weekday}Terça"
    old "{#weekday}Wednesday"
    new "{#weekday}Quarta"
    old "{#weekday}Thursday"
    new "{#weekday}Quinta"
    old "{#weekday}Friday"
    new "{#weekday}Sexta"
    old "{#weekday}Saturday"
    new "{#weekday}Sábado"
    old "{#weekday}Sunday"
    new "{#weekday}Domingo"
    old "{#weekday_short}Mon"
    new "{#weekday_short}Seg"
    old "{#weekday_short}Tue"
    new "{#weekday_short}Ter"
    old "{#weekday_short}Wed"
    new "{#weekday_short}Qua"
    old "{#weekday_short}Thu"
    new "{#weekday_short}Qui"
    old "{#weekday_short}Fri"
    new "{#weekday_short}Sex"
    old "{#weekday_short}Sat"
    new "{#weekday_short}Sáb"
    old "{#weekday_short}Sun"
    new "{#weekday_short}Dom"
    old "{#month}January"
    new "{#month}Janeiro"
    old "{#month}February"
    new "{#month}Fevereiro"
    old "{#month}March"
    new "{#month}Março"
    old "{#month}April"
    new "{#month}Abril"
    old "{#month}May"
    new "{#month}Maio"
    old "{#month}June"
    new "{#month}Junho"
    old "{#month}July"
    new "{#month}Julho"
    old "{#month}August"
    new "{#month}Agosto"
    old "{#month}September"
    new "{#month}Setembro"
    old "{#month}October"
    new "{#month}Outubro"
    old "{#month}November"
    new "{#month}Novembro"
    old "{#month}December"
    new "{#month}Dezembro"
    old "{#month_short}Jan"
    new "{#month_short}Jan"
    old "{#month_short}Feb"
    new "{#month_short}Fev"
    old "{#month_short}Mar"
    new "{#month_short}Mar"
    old "{#month_short}Apr"
    new "{#month_short}Abr"
    old "{#month_short}May"
    new "{#month_short}Mai"
    old "{#month_short}Jun"
    new "{#month_short}Jun"
    old "{#month_short}Jul"
    new "{#month_short}Jul"
    old "{#month_short}Aug"
    new "{#month_short}Ago"
    old "{#month_short}Sep"
    new "{#month_short}Set"
    old "{#month_short}Oct"
    new "{#month_short}Out"
    old "{#month_short}Nov"
    new "{#month_short}Nov"
    old "{#month_short}Dec"
    new "{#month_short}Dez"
    old "%b %d, %H:%M"
    new "%d %b, %H:%M"
    old "Save slot %s: [text]"
    new "Salvar no slot %s: [text]"
    old "Load slot %s: [text]"
    new "Carregar slot %s: [text]"
    old "Delete slot [text]"
    new "Deletar slot [text]"
    old "File page auto"
    new "Página do arquivo (s. auto)"
    old "File page quick"
    new "Página do arquivo (s. rápido)"
    old "File page [text]"
    new "Página [text] do arquivo"
    old "Next file page."
    new "Página seguinte do arquivo."
    old "Previous file page."
    new "Página anterior do arquivo."
    old "Quick save complete."
    new "Salvamento rápido concluído."
    old "Quick save."
    new "Salvamento rápido."
    old "Quick load."
    new "Carregamento rápido."
    old "Language [text]"
    new "Idioma [text]"
    old "Open [text] directory."
    new "Abrir diretório [text]."
    old "Are you sure?"
    new "Você tem certeza?"
    old "Are you sure you want to delete this save?"
    new "Você tem certeza que deseja deletar este save?"
    old "Are you sure you want to overwrite your save?"
    new "Você tem certeza que deseja sobrescrever este save?"
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new "Ao carregar, qualquer progresso não salvo será perdido.\nVocê tem certeza que deseja fazer isso?"
    old "Are you sure you want to quit?"
    new "Você tem certeza que deseja sair?"
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new "Você tem certeza que deseja voltar para o menu principal?\nQualquer progresso não salvo será perdido."
    old "Are you sure you want to end the replay?"
    new "Você tem certeza que deseja encerrar o replay?"
    old "Are you sure you want to begin skipping?"
    new "Você tem certeza que deseja começar a pular o diálogo?"
    old "Are you sure you want to skip to the next choice?"
    new "Você tem certeza que deseja pular o diálogo até a próxima escolha?"
    old "Are you sure you want to skip unseen dialogue to the next choice?"
    new "Você tem certeza que deseja pular o diálogo ainda não visto até a próxima escolha?"
    old "Failed to save screenshot as %s."
    new "Falha ao salvar captura de tela em %s."
    old "Saved screenshot as %s."
    new "Captura de tela salva em %s."
    old "Skip Mode"
    new "Modo de Pulo de Diálogo"
    old "This program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license}here{/a}."
    new "Este programa contém software livre sob diferentes licenças, incluindo a Licença MIT e a GNU LGPL. A lista completa dos softwares, incluindo links para o código fonte completo, pode ser encontrado {a=https://www.renpy.org/l/license}aqui{/a}."
    old "Clipboard voicing enabled. Press 'shift+C' to disable."
    new "Narração da área de transferência habilitada. Pressione 'Shift+C' para desabilitar."
    old "Self-voicing would say \"[renpy.display.tts.last]\". Press 'alt+shift+V' to disable."
    new "A narração assistiva diria \"[renpy.display.tts.last]\". Pressione 'Alt+Shift+V' para desabilitar."
    old "Self-voicing enabled. Press 'v' to disable."
    new "Narração assistiva habilitada. Pressione 'V' para desabilitar."
    old "Renderer"
    new "Renderizador"
    old "Automatically Choose"
    new "Escolher Automaticamente"
    old "Force GL Renderer"
    new "Forçar Renderizador GL"
    old "Force ANGLE Renderer"
    new "Forçar Renderizador ANGLE"
    old "Force GLES Renderer"
    new "Forçar Renderizador GLES"
    old "Force GL2 Renderer"
    new "Forçar Renderizador GL2"
    old "Force ANGLE2 Renderer"
    new "Forçar Renderizador ANGLE2"
    old "Force GLES2 Renderer"
    new "Forçar Renderizador GLES2"
    old "Enable (No Blocklist)"
    new "Habilitar (Sem Lista de Bloqueio)"
    old "Powersave"
    new "Economia de Energia"
    old "Framerate"
    new "Taxa de Quadros"
    old "Screen"
    new "Máximo Suportado pela Tela"
    old "60"
    new "60"
    old "30"
    new "30"
    old "Tearing"
    new "Tearing"
    old "Changes will take effect the next time this program is run."
    new "As alterações serão aplicadas na próxima vez que este jogo for executado."
    old "Performance Warning"
    new "Aviso de Performance"
    old "This computer is using software rendering."
    new "Este dispositivo está usando renderização via software."
    old "This game requires use of GL2 that can't be initialised."
    new "Este jogo requer o uso de GL2, que não pode ser inicializado."
    old "This computer has a problem displaying graphics: [problem]."
    new "Este dispositivo está com um problema na exibição de gráficos: [problem]."
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display."
    new "Os drivers gráficos podem estar desatualizados ou sem funcionar direito. Isso pode causar lentidão ou uma exibição incorreta dos gráficos."
    old "The {a=edit:1:log.txt}log.txt{/a} file may contain information to help you determine what is wrong with your computer."
    new "O arquivo {a=edit:1:log.txt}log.txt{/a} pode conter informações que ajudarão a determinar o que há de errado com seu dispositivo."
    old "More details on how to fix this can be found in the {a=[url]}documentation{/a}."
    new "Mais detalhes sobre como corrigir isso podem ser encontrados na {a=[url]}documentação{/a}."
    old "Continue, Show this warning again"
    new "Continuar, Mostrar este aviso novamente"
    old "Continue, Don't show warning again"
    new "Continuar, Não mostrar este aviso novamente"
    old "Change render options"
    new "Alterar opções de renderização"
    old "Select Gamepad to Calibrate"
    new "Selecione o Controle para Calibrar"
    old "No Gamepads Available"
    new "Não há Controles Disponíveis"
    old "Calibrating [name] ([i]/[total])"
    new "Calibrando [name] ([i]/[total])"
    old "Press or move the '[control!s]' [kind]."
    new "Pressione ou movimente os [kind] '[control!s]'"
    old "Skip (A)"
    new "Pular (A)"
    old "Back (B)"
    new "Voltar (B)"
    old "Open"
    new "Abrir"
    old "Opens the traceback.txt file in a text editor."
    new ""
    old "Copy BBCode"
    new ""
    old "Copies the traceback.txt file to the clipboard as BBcode for forums like https://lemmasoft.renai.us/."
    new ""
    old "Copy Markdown"
    new ""
    old "Copies the traceback.txt file to the clipboard as Markdown for Discord."
    new ""
    old "An exception has occurred."
    new ""
    old "Rollback"
    new ""
    old "Attempts a roll back to a prior time, allowing you to save or choose a different choice."
    new ""
    old "Ignore"
    new ""
    old "Ignores the exception, allowing you to continue."
    new ""
    old "Ignores the exception, allowing you to continue. This often leads to additional errors."
    new ""
    old "Reload"
    new ""
    old "Reloads the game from disk, saving and restoring game state if possible."
    new ""
    old "Console"
    new ""
    old "Opens a console to allow debugging the problem."
    new ""
    old "Quits the game."
    new ""
    old "Parsing the script failed."
    new ""
    old "Back"
    new ""
    old "History"
    new ""
    old "Skip"
    new ""
    old "Auto"
    new ""
    old "Save"
    new ""
    old "Q.Save"
    new ""
    old "Q.Load"
    new ""
    old "Prefs"
    new ""
    old "Start"
    new ""
    old "Load"
    new ""
    old "Preferences"
    new ""
    old "End Replay"
    new ""
    old "Main Menu"
    new ""
    old "Credits"
    new ""
    old "Quit"
    new ""
    old "Return"
    new ""
    old "Page {}"
    new ""
    old "Automatic saves"
    new ""
    old "Quick saves"
    new ""
    old "{#file_time}%A, %B %d %Y, %H:%M"
    new ""
    old "empty slot"
    new ""
    old "<"
    new ""
    old ">"
    new ""
    old "Display"
    new ""
    old "Window"
    new ""
    old "Fullscreen"
    new ""
    old "Unseen Text"
    new ""
    old "After Choices"
    new ""
    old "Transitions"
    new ""
    old "Text Speed"
    new ""
    old "Auto-Forward Time"
    new ""
    old "Music Volume"
    new ""
    old "Sound Volume"
    new ""
    old "Test"
    new ""
    old "Mute All"
    new ""
    old "The dialogue history is empty."
    new ""
    old "Help"
    new ""
    old "Keyboard"
    new ""
    old "Mouse"
    new ""
    old "Gamepad"
    new ""
    old "Enter"
    new ""
    old "Advances dialogue and activates the interface."
    new ""
    old "Space"
    new ""
    old "Advances dialogue without selecting choices."
    new ""
    old "Arrow Keys"
    new ""
    old "Navigate the interface."
    new ""
    old "Escape"
    new ""
    old "Accesses the game menu."
    new ""
    old "Ctrl"
    new ""
    old "Skips dialogue while held down."
    new ""
    old "Tab"
    new ""
    old "Toggles dialogue skipping."
    new ""
    old "Page Up"
    new ""
    old "Rolls back to earlier dialogue."
    new ""
    old "Page Down"
    new ""
    old "Rolls forward to later dialogue."
    new ""
    old "Hides the user interface."
    new ""
    old "Takes a screenshot."
    new ""
    old "Toggles assistive {a=https://www.renpy.org/l/voicing}self-voicing{/a}."
    new ""
    old "Left Click"
    new ""
    old "Middle Click"
    new ""
    old "Right Click"
    new ""
    old "Mouse Wheel Up\nClick Rollback Side"
    new ""
    old "Mouse Wheel Down"
    new ""
    old "Right Trigger\nA/Bottom Button"
    new ""
    old "Left Trigger\nLeft Shoulder"
    new ""
    old "Right Shoulder"
    new ""
    old "D-Pad, Sticks"
    new ""
    old "Start, Guide"
    new ""
    old "Y/Top Button"
    new ""
    old "Calibrate"
    new ""
    old "Yes"
    new ""
    old "No"
    new ""
    old "Skipping"
    new ""
    old "Menu"
    new ""
    old "FurryBoss"
    new ""
    old "Made by"
    new ""
    old "Art"
    new ""
    old "Music"
    new ""
    old "Additional help"
    new ""
    old "Portuguese translation"
    new ""
    old "Language"
    new ""
    old "English"
    new ""
    old "Português"
    new ""
