translate portuguese strings:
    old "Self-voicing disabled."
    new "Narração assistiva desabilitada."
    old "Clipboard voicing enabled. "
    new "Narração da área de transferência habilitada. "
    old "Self-voicing enabled. "
    new "Narração assistiva habilitada. "
    old "Font Override"
    new "Substituição de Fonte"
    old "Default"
    new "Padrão"
    old "DejaVu Sans"
    new "DejaVu Sans"
    old "Opendyslexic"
    new "Opendyslexic"
    old "Text Size Scaling"
    new "Escala do Tamanho do Texto"
    old "Reset"
    new "Resetar"
    old "Line Spacing Scaling"
    new "Escala do Espaçamento entre Linhas"
    old "High Contrast Text"
    new "Texto de Alto Contraste"
    old "Enable"
    new "Habilitar"
    old "Disable"
    new "Desabilitar"
    old "Self-Voicing"
    new "Narração Assistiva"
    old "Off"
    new "Desabilitado"
    old "Text-to-speech"
    new "Texto para Fala"
    old "Clipboard"
    new "Área de Transferência"
    old "Debug"
    new "Depurar"
    old "Self-Voicing Volume Drop"
    new "Redução de Volume da Narração Assistiva"
    old "The options on this menu are intended to improve accessibility. They may not work with all games, and some combinations of options may render the game unplayable. This is not an issue with the game or engine. For the best results when changing fonts, try to keep the text size the same as it originally was."
    new "As opções nesse menu visam melhorar a accessibilidade. Elas não vão funcionar com todos os jogos, e algumas combinações de opções podem deixar o game injogável. Isso não é um problema com o jogo ou a engine. Para melhores resultados mudando fontes, tente manter o tamanho do texto igual ao que era originalmente."
    old "{#weekday}Monday"
    new "{#weekday}Segunda"
    old "{#weekday}Tuesday"
    new "{#weekday}Terça"
    old "{#weekday}Wednesday"
    new "{#weekday}Quarta"
    old "{#weekday}Thursday"
    new "{#weekday}Quinta"
    old "{#weekday}Friday"
    new "{#weekday}Sexta"
    old "{#weekday}Saturday"
    new "{#weekday}Sábado"
    old "{#weekday}Sunday"
    new "{#weekday}Domingo"
    old "{#weekday_short}Mon"
    new "{#weekday_short}Seg"
    old "{#weekday_short}Tue"
    new "{#weekday_short}Ter"
    old "{#weekday_short}Wed"
    new "{#weekday_short}Qua"
    old "{#weekday_short}Thu"
    new "{#weekday_short}Qui"
    old "{#weekday_short}Fri"
    new "{#weekday_short}Sex"
    old "{#weekday_short}Sat"
    new "{#weekday_short}Sáb"
    old "{#weekday_short}Sun"
    new "{#weekday_short}Dom"
    old "{#month}January"
    new "{#month}Janeiro"
    old "{#month}February"
    new "{#month}Fevereiro"
    old "{#month}March"
    new "{#month}Março"
    old "{#month}April"
    new "{#month}Abril"
    old "{#month}May"
    new "{#month}Maio"
    old "{#month}June"
    new "{#month}Junho"
    old "{#month}July"
    new "{#month}Julho"
    old "{#month}August"
    new "{#month}Agosto"
    old "{#month}September"
    new "{#month}Setembro"
    old "{#month}October"
    new "{#month}Outubro"
    old "{#month}November"
    new "{#month}Novembro"
    old "{#month}December"
    new "{#month}Dezembro"
    old "{#month_short}Jan"
    new "{#month_short}Jan"
    old "{#month_short}Feb"
    new "{#month_short}Fev"
    old "{#month_short}Mar"
    new "{#month_short}Mar"
    old "{#month_short}Apr"
    new "{#month_short}Abr"
    old "{#month_short}May"
    new "{#month_short}Mai"
    old "{#month_short}Jun"
    new "{#month_short}Jun"
    old "{#month_short}Jul"
    new "{#month_short}Jul"
    old "{#month_short}Aug"
    new "{#month_short}Ago"
    old "{#month_short}Sep"
    new "{#month_short}Set"
    old "{#month_short}Oct"
    new "{#month_short}Out"
    old "{#month_short}Nov"
    new "{#month_short}Nov"
    old "{#month_short}Dec"
    new "{#month_short}Dez"
    old "%b %d, %H:%M"
    new "%d %b, %H:%M"
    old "Save slot %s: [text]"
    new ""
    old "Load slot %s: [text]"
    new ""
    old "Delete slot [text]"
    new ""
    old "File page auto"
    new ""
    old "File page quick"
    new ""
    old "File page [text]"
    new ""
    old "Next file page."
    new ""
    old "Previous file page."
    new ""
    old "Quick save complete."
    new ""
    old "Quick save."
    new ""
    old "Quick load."
    new ""
    old "Language [text]"
    new ""
    old "Open [text] directory."
    new ""
    old "Are you sure?"
    new ""
    old "Are you sure you want to delete this save?"
    new ""
    old "Are you sure you want to overwrite your save?"
    new ""
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new ""
    old "Are you sure you want to quit?"
    new ""
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new ""
    old "Are you sure you want to end the replay?"
    new ""
    old "Are you sure you want to begin skipping?"
    new ""
    old "Are you sure you want to skip to the next choice?"
    new ""
    old "Are you sure you want to skip unseen dialogue to the next choice?"
    new ""
    old "Failed to save screenshot as %s."
    new ""
    old "Saved screenshot as %s."
    new ""
    old "Skip Mode"
    new ""
    old "This program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license}here{/a}."
    new ""
    old "Clipboard voicing enabled. Press 'shift+C' to disable."
    new ""
    old "Self-voicing would say \"[renpy.display.tts.last]\". Press 'alt+shift+V' to disable."
    new ""
    old "Self-voicing enabled. Press 'v' to disable."
    new ""
    old "Renderer"
    new ""
    old "Automatically Choose"
    new ""
    old "Force GL Renderer"
    new ""
    old "Force ANGLE Renderer"
    new ""
    old "Force GLES Renderer"
    new ""
    old "Force GL2 Renderer"
    new ""
    old "Force ANGLE2 Renderer"
    new ""
    old "Force GLES2 Renderer"
    new ""
    old "Enable (No Blocklist)"
    new ""
    old "Powersave"
    new ""
    old "Framerate"
    new ""
    old "Screen"
    new ""
    old "60"
    new ""
    old "30"
    new ""
    old "Tearing"
    new ""
    old "Changes will take effect the next time this program is run."
    new ""
    old "Performance Warning"
    new ""
    old "This computer is using software rendering."
    new ""
    old "This game requires use of GL2 that can't be initialised."
    new ""
    old "This computer has a problem displaying graphics: [problem]."
    new ""
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display."
    new ""
    old "The {a=edit:1:log.txt}log.txt{/a} file may contain information to help you determine what is wrong with your computer."
    new ""
    old "More details on how to fix this can be found in the {a=[url]}documentation{/a}."
    new ""
    old "Continue, Show this warning again"
    new ""
    old "Continue, Don't show warning again"
    new ""
    old "Change render options"
    new ""
    old "Select Gamepad to Calibrate"
    new ""
    old "No Gamepads Available"
    new ""
    old "Calibrating [name] ([i]/[total])"
    new ""
    old "Press or move the '[control!s]' [kind]."
    new ""
    old "Skip (A)"
    new ""
    old "Back (B)"
    new ""
    old "Open"
    new ""
    old "Opens the traceback.txt file in a text editor."
    new ""
    old "Copy BBCode"
    new ""
    old "Copies the traceback.txt file to the clipboard as BBcode for forums like https://lemmasoft.renai.us/."
    new ""
    old "Copy Markdown"
    new ""
    old "Copies the traceback.txt file to the clipboard as Markdown for Discord."
    new ""
    old "An exception has occurred."
    new ""
    old "Rollback"
    new ""
    old "Attempts a roll back to a prior time, allowing you to save or choose a different choice."
    new ""
    old "Ignore"
    new ""
    old "Ignores the exception, allowing you to continue."
    new ""
    old "Ignores the exception, allowing you to continue. This often leads to additional errors."
    new ""
    old "Reload"
    new ""
    old "Reloads the game from disk, saving and restoring game state if possible."
    new ""
    old "Console"
    new ""
    old "Opens a console to allow debugging the problem."
    new ""
    old "Quits the game."
    new ""
    old "Parsing the script failed."
    new ""
    old "Back"
    new ""
    old "History"
    new ""
    old "Skip"
    new ""
    old "Auto"
    new ""
    old "Save"
    new ""
    old "Q.Save"
    new ""
    old "Q.Load"
    new ""
    old "Prefs"
    new ""
    old "Start"
    new ""
    old "Load"
    new ""
    old "Preferences"
    new ""
    old "End Replay"
    new ""
    old "Main Menu"
    new ""
    old "Credits"
    new ""
    old "Quit"
    new ""
    old "Return"
    new ""
    old "Page {}"
    new ""
    old "Automatic saves"
    new ""
    old "Quick saves"
    new ""
    old "{#file_time}%A, %B %d %Y, %H:%M"
    new ""
    old "empty slot"
    new ""
    old "<"
    new ""
    old ">"
    new ""
    old "Display"
    new ""
    old "Window"
    new ""
    old "Fullscreen"
    new ""
    old "Unseen Text"
    new ""
    old "After Choices"
    new ""
    old "Transitions"
    new ""
    old "Text Speed"
    new ""
    old "Auto-Forward Time"
    new ""
    old "Music Volume"
    new ""
    old "Sound Volume"
    new ""
    old "Test"
    new ""
    old "Mute All"
    new ""
    old "The dialogue history is empty."
    new ""
    old "Help"
    new ""
    old "Keyboard"
    new ""
    old "Mouse"
    new ""
    old "Gamepad"
    new ""
    old "Enter"
    new ""
    old "Advances dialogue and activates the interface."
    new ""
    old "Space"
    new ""
    old "Advances dialogue without selecting choices."
    new ""
    old "Arrow Keys"
    new ""
    old "Navigate the interface."
    new ""
    old "Escape"
    new ""
    old "Accesses the game menu."
    new ""
    old "Ctrl"
    new ""
    old "Skips dialogue while held down."
    new ""
    old "Tab"
    new ""
    old "Toggles dialogue skipping."
    new ""
    old "Page Up"
    new ""
    old "Rolls back to earlier dialogue."
    new ""
    old "Page Down"
    new ""
    old "Rolls forward to later dialogue."
    new ""
    old "Hides the user interface."
    new ""
    old "Takes a screenshot."
    new ""
    old "Toggles assistive {a=https://www.renpy.org/l/voicing}self-voicing{/a}."
    new ""
    old "Left Click"
    new ""
    old "Middle Click"
    new ""
    old "Right Click"
    new ""
    old "Mouse Wheel Up\nClick Rollback Side"
    new ""
    old "Mouse Wheel Down"
    new ""
    old "Right Trigger\nA/Bottom Button"
    new ""
    old "Left Trigger\nLeft Shoulder"
    new ""
    old "Right Shoulder"
    new ""
    old "D-Pad, Sticks"
    new ""
    old "Start, Guide"
    new ""
    old "Y/Top Button"
    new ""
    old "Calibrate"
    new ""
    old "Yes"
    new ""
    old "No"
    new ""
    old "Skipping"
    new ""
    old "Menu"
    new ""
    old "FurryBoss"
    new ""
    old "Made by"
    new ""
    old "Art"
    new ""
    old "Music"
    new ""
    old "Additional help"
    new ""
    old "Portuguese translation"
    new ""
    old "Language"
    new ""
    old "English"
    new ""
    old "Português"
    new ""
